os: linux

# we use the R VM because it contains LaTeX and pandoc
language: r

# we need super user privileges, so we depend on the old travis-ci infrastructure
sudo: required

script:
# in the next step we use pdflatex to convert .tex to .pdf
  - pdflatex sigproc_mka.tex